Repository getdokan/storegrowth-sales-booster, pull requests merged in 2025-08, with the labels that each got.

#445 🛠 refactor: Global functions into Helper class
  composer.json
  includes/Assets.php
  includes/Helper.php
  includes/functions.php
  includes/index.php
  modules/bogo/BoGoModule.php
  modules/bogo/includes/EnqueueScript.php
  modules/bogo/templates/bogo-upgrade-notice.php
  modules/countdown-timer/CountdownTimerModule.php
  modules/countdown-timer/includes/EnqueueScript.php
  modules/countdown-timer/templates/countdown-timer.php
  modules/direct-checkout/DirectCheckoutModule.php
  modules/direct-checkout/includes/CommonHooks.php
  modules/direct-checkout/includes/EnqueueScript.php
  modules/direct-checkout/templates/buy-now-button-template.php
  modules/direct-checkout/templates/loop/buy-to-cart.php
  modules/floating-notification-bar/FloatingNotificationBarModule.php
  modules/floating-notification-bar/includes/CommonHooks.php
  modules/floating-notification-bar/includes/EnqueueScript.php
  modules/floating-notification-bar/includes/Helper.php
  modules/floating-notification-bar/templates/bar.php
  modules/fly-cart/FlyCartModule.php
  modules/fly-cart/includes/CommonHooks.php
  modules/fly-cart/includes/EnqueueScript.php
  modules/fly-cart/templates/cart-contents.php
  modules/fly-cart/templates/fly-cart.php
  modules/progressive-discount-banner/ProgressiveDiscountBannerModule.php
  modules/progressive-discount-banner/includes/CommonHooks.php
  modules/progressive-discount-banner/includes/EnqueueScript.php
  modules/progressive-discount-banner/includes/Helper.php
  modules/progressive-discount-banner/includes/WoocommerceDiscount.php
  modules/progressive-discount-banner/templates/bar.php
  modules/quick-view/QuickViewModule.php
  modules/quick-view/includes/Ajax.php
  modules/quick-view/includes/CommonHooks.php
  modules/quick-view/includes/EnqueueScript.php
  modules/quick-view/templates/quick-view-button.php
  modules/sales-pop/SalesPopModule.php
  modules/sales-pop/includes/EnqueueScript.php
  modules/stock-bar/StockBarModule.php
  modules/stock-bar/includes/EnqueueScript.php
  modules/stock-bar/templates/simple-stock-status.php
  modules/upsell-order-bump/UpsellOrderBumpModule.php
  modules/upsell-order-bump/includes/EnqueueScript.php
Labels: Need Dev Review

#429 feat: Quick view button level validation
  Includes/Modules/QuickView/assets/src/components/ButtonSettingsTab.jsx
  assets/src/admin.scss
  assets/src/components/settings/Panels/PanelSettings/Fields/TextInput.js
Labels: Need Dev Review, Need Testing

#430 🎯 fix: Input validation to the product discount countdown timer percentage field
  Includes/Modules/CountdownTimer/templates/wc-product-data-panels.php
Labels: Need Dev Review, Need Testing

#431 feat: add status prop to number input component
  assets/src/components/settings/Panels/PanelSettings/Fields/Number.js
Labels: Need Dev Review

#432 🎯 fix: Buy now button missing for stock out products
  Includes/Modules/DirectCheckout/Includes/CommonHooks.php
  Includes/Modules/DirectCheckout/assets/css/sgsb-dc-style.css
  Includes/Modules/DirectCheckout/assets/js/sgsb-dc-script.js
  Includes/Modules/DirectCheckout/templates/buy-now-button-template.php
  Includes/Modules/FlyCart/assets/js/wfc-script.js
Labels: Need Dev Review, Need Testing

#433 🎨 update: Action button hover effects in banners
  Includes/Modules/FloatingNotificationBar/assets/css/floating-notification-bar.css
Labels: Need Dev Review, Need Testing

#435 fix: add validation handling to floating notification bar components
  Includes/Modules/FloatingNotificationBar/assets/src/components/DefaultBanner.js
  Includes/Modules/FloatingNotificationBar/assets/src/components/FloatingNotificationBarLayout.js
  Includes/Modules/FloatingNotificationBar/assets/src/components/SettingsTab.js
Labels: Need Dev Review, Need Testing

#436 🚀 enhance: Validation of banner close redirect URL input
  Includes/Modules/FloatingNotificationBar/assets/src/components/ButtonAction.js
  Includes/Modules/FloatingNotificationBar/assets/src/components/FloatingNotificationBarLayout.js
Labels: Need Dev Review, Need Testing

#437 🎨 enhance: Update quick view button default styling
  Includes/Modules/QuickView/Includes/EnqueueScript.php
  Includes/Modules/QuickView/assets/src/components/QuickViewLayout.jsx
Labels: Need Dev Review, Need Testing

#438 🪝 new: Introduced new hooks to the FlyCart mudule for extendibility support
  Includes/Modules/FlyCart/assets/src/components/index.js
  Includes/Modules/FlyCart/templates/cart-contents.php
Labels: Need Dev Review

#439 fix: Overlapping free shipping and floating bars on storefront
  Includes/Modules/FloatingNotificationBar/Includes/EnqueueScript.php
  Includes/Modules/FloatingNotificationBar/assets/js/sgsb-pd-banner-bar-remove.js
  Includes/Modules/ProgressiveDiscountBanner/assets/js/sgsb-pd-banner-bar-remove.js
  Includes/functions.php
Labels: Need Dev Review, Need Testing

#440 feat: integrate WordPress hooks for countdown timer data and tab panels
  Includes/Modules/CountdownTimer/assets/src/components/SalesCountdownLayout.js
Labels: Need Testing, Dev Review Done

#462 fix: center items in floating notification bar and improve layout
  modules/floating-notification-bar/assets/css/floating-notification-bar.css
  modules/floating-notification-bar/assets/src/components/Preview.js
  modules/floating-notification-bar/assets/src/components/Templates/NotifyBarOne.js
  modules/floating-notification-bar/templates/bar.php
Labels: Need Dev Review, Need Testing

#453 fix: update YouTube link in Ready component
  assets/src/components/initail-setup/Ready.jsx
Labels: Need Dev Review

#468 🎯 fix: General settings data was not saving on sales notification module
  modules/sales-pop/includes/Ajax.php
Labels: Need Dev Review, Need Testing

#457 Add currency formatting and accounting utilities.
  assets/src/definitions/window-types.ts
  assets/src/definitions/woocommerce-accounting.d.ts
  assets/src/utils/Accounting.ts
  includes/Assets.php
  modules/upsell-order-bump/assets/src/components/OfferProductContent.js
Labels: Need Dev Review, Need Testing

#474 🎯 fix: Discount amount option was not working for progressive discount
  modules/progressive-discount-banner/includes/WoocommerceDiscount.php
Labels: Dev Review Done
